# Generated by Django 3.1.7 on 2021-04-19 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20210419_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='deal_stage',
            field=models.CharField(blank=True, choices=[('collected sample pack', 'Collected Sample Pack'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('appointment booked', 'Appointment Booked'), ('purchased', 'Purchased'), ('closed lost', 'Closed (Lost)'), ('closed won', 'Closed (Won)'), ('complained', 'Complained'), ('refund', 'Refund')], max_length=50, null=True),
        ),
    ]
