# Generated by Django 3.1.7 on 2021-04-19 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20210419_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contact_method',
            field=models.CharField(blank=True, choices=[('Phone Call', 'Phone Call'), ('Email', 'Email'), ('WhatsApp', 'WhatsApp'), ('Text', 'Text'), ('Do Not Contact', 'Do Not Contact')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='pdpa_agreed',
            field=models.BooleanField(default=True, help_text='Customer has agreed to PDPA rules.'),
            preserve_default=False,
        ),
    ]
