# Generated by Django 3.1.7 on 2021-04-19 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20210419_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pdpa_agreed',
            field=models.BooleanField(help_text='Customer has agreed to PDPA rules.', verbose_name='PDPA Acknowledged'),
        ),
    ]
